name: Publish Linux
on:
    push:
        branches:
            - main

permissions:
    contents: write

jobs:
    publish:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Install Poetry
              run: pipx install poetry
            - name: Install Dependencies
              run: poetry install
            - name: Build Artifacts
              run: |
                  poetry run briefcase create
                  poetry run briefcase build
                  poetry run briefcase package
            - name: Tag release
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              run: |
                  VERSION=$(poetry version --short)
                  git config user.name "github-actions[bot]"
                  git config user.email "github-actions[bot]@users.noreply.github.com"
                  gh release create "Linux-v$VERSION" ./dist/* --notes-file ./CHANGELOG.md
