name: Publish Linux (Arch)
on:
    push:
        branches:
            - main

permissions:
    contents: write

jobs:
    publish:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Install UV
              run: curl -LsSf https://astral.sh/uv/install.sh | sh
            - name: Install Python
              run: uv python install 3.14
            - name: Stage CHANGELOG for Briefcase
              run: cp CHANGELOG.md CHANGELOG
            - name: Build Artifacts
              run: |
                  uv run briefcase create linux system --target archlinux:latest
                  uv run briefcase build linux system --target archlinux:latest
                  uv run briefcase package linux system --target archlinux:latest
            - name: Tag release
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              run: |
                  VERSION=$(uv version --short)
                  git config user.name "github-actions[bot]"
                  git config user.email "github-actions[bot]@users.noreply.github.com"
                  gh release create "Arch-v$VERSION" ./dist/* --notes-file ./CHANGELOG.md
