name: Publish Linux
on:
    push:
        branches:
            - main

permissions:
    contents: write

jobs:
    publish:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Install Poetry
              run: pipx install poetry
            - name: Install Dependencies
              run: poetry install
            - name: Build Artifacts
              run: |
                  poetry run briefcase create
                  poetry run briefcase build
                  poetry run briefcase package
            - name: Upload Artifacts
              uses: actions/upload-artifact@v7
              with:
                  name: PowerMouse
                  path: dist/
                  if-no-files-found: error
            - name: Tag release
              run: |
                  VERSION=$(poetry version --short)
                  git config user.name "github-actions[bot]"
                  git config user.email "github-actions[bot]@users.noreply.github.com"
                  git tag "Linux v$VERSION"
                  git push origin "Linux v$VERSION"
