name: Publish Windows
on:
    push:
        branches:
            - main

permissions:
    contents: write

jobs:
    publish:
        runs-on: windows-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
            - name: Install Poetry
              run: python -m pipx install poetry
            - name: Install dependencies
              run: poetry install
            - name: Build Artifacts
              run: |
                  poetry run briefcase create
                  poetry run briefcase build
                  poetry run briefcase package
            - name: Upload Artifacts
              uses: actions/upload-artifact@v7
              with:
                  name: PowerMouse
                  path: dist/
                  if-no-files-found: error
            - name: Tag release
              run: |
                  $VERSION = (&poetry version --short).Trim()
                  git config user.name "github-actions[bot]"
                  git config user.email "github-actions[bot]@users.noreply.github.com"
                  git tag "Windows-$VERSION"
                  git push origin "Windows-$VERSION"
