name: Publish Windows
on:
    push:
        branches:
            - main

permissions:
    contents: write

jobs:
    publish:
        runs-on: windows-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
            - name: Install Poetry
              run: python -m pipx install poetry
            - name: Install dependencies
              run: poetry install
            - name: Build Artifacts
              run: |
                  poetry run briefcase create
                  poetry run briefcase build
                  poetry run briefcase package
            - name: Release
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              run: |
                  $VERSION = (&poetry version --short).Trim()
                  git config user.name "github-actions[bot]"
                  git config user.email "github-actions[bot]@users.noreply.github.com"
                  gh release create "Windows-v$VERSION" ./dist/* --notes-file ./CHANGELOG.md
